[package]
name = "inspect_path"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_Storage_FileSystem"] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.31.0", features = ["fs"] }
